ARG PYTHON_VERSION
ARG BASE_IMAGE_VERSION

FROM python:${PYTHON_VERSION}-${BASE_IMAGE_VERSION}

RUN apt update && apt upgrade -y

# those packages come with the non-slim image
RUN apt install --no-install-recommends -y \
    bash \
    ca-certificates \
    curl \
    git \
    openssl
