ARG PYTHON_VERSION
ARG BASE_IMAGE_VERSION

FROM python:${PYTHON_VERSION}-${BASE_IMAGE_VERSION}

RUN apt-get update && \
    apt-get upgrade -y && \
    apt install --no-install-recommends -y \
        bash \
        ca-certificates \
        curl \
        git \
        gcc \
        make \
        openssl \
        ssh \
    && \
    rm -rf /var/lib/apt/lists/*
    
