ARG PYTHON_VERSION
ARG BASE_IMAGE_VERSION

FROM python:${PYTHON_VERSION}-alpine${BASE_IMAGE_VERSION}

RUN apk update && apk upgrade

RUN apk add --no-cache \
    bash \
    ca-certificates \
    curl \
    git \
    openssl
