ARG PYTHON_VERSION
ARG BASE_IMAGE_VERSION

FROM python:${PYTHON_VERSION}-${BASE_IMAGE_VERSION}

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        bash \
        ca-certificates \
        curl \
        git \
        make \
        openssl \
        openssh \
    ;
