name: build_and_release

on:
  schedule:
    - cron: "0 10 * * 1"

  push:
    tags: ["v*.*.*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]
        version: ["alpine3.18", "bookworm", "slim-bookworm"]
        include:
          - version: "alpine3.18"
            file: "alpine"
          - version: "bookworm"
            file: "debian"
          - version: "slim-bookworm"
            file: "debian"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python-dev
          flavor: |
            latest=auto
            prefix=${{ matrix.python }}-${{ matrix.version }}-,onlatest=true
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile.${{ matrix.file }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            BASE_IMAGE_VERSION=${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
